version: "3.1"

services:
  database:
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - JWT_KEY=XXXXX
      - JWT_EXPIRES_IN=XX
      - GOOGLE_API_KEY=AIXXXXX

volumes:
  postgres_data:
